/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stdio.h"
#include "stdlib.h"
#include "stdbool.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_EDIT_0    (GUI_ID_USER + 0x01)
#define ID_EDIT_1    (GUI_ID_USER + 0x02)
#define ID_BUTTON_0    (GUI_ID_USER + 0x03)
#define ID_BUTTON_1    (GUI_ID_USER + 0x04)
#define ID_BUTTON_2    (GUI_ID_USER + 0x05)
#define ID_BUTTON_3    (GUI_ID_USER + 0x06)
#define ID_BUTTON_4    (GUI_ID_USER + 0x07)
#define ID_BUTTON_5    (GUI_ID_USER + 0x08)
#define ID_BUTTON_6    (GUI_ID_USER + 0x09)
#define ID_BUTTON_7    (GUI_ID_USER + 0x0A)
#define ID_BUTTON_8    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_9    (GUI_ID_USER + 0x0C)
#define ID_TEXT_0    (GUI_ID_USER + 0x0D)

// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmrat_up;
extern GUI_CONST_STORAGE GUI_BITMAP bmrat_down;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "game_rat", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Time", ID_EDIT_0, 4, 6, 86, 27, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Money", ID_EDIT_1, 389, 6, 86, 27, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "start_but", ID_BUTTON_0, 189, 6, 86, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_1", ID_BUTTON_1, 101, 71, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_2", ID_BUTTON_2, 210, 71, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_3", ID_BUTTON_3, 320, 71, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_4", ID_BUTTON_4, 102, 142, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_5", ID_BUTTON_5, 210, 142, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_6", ID_BUTTON_6, 320, 142, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_7", ID_BUTTON_7, 102, 210, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_8", ID_BUTTON_8, 210, 210, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "but_9", ID_BUTTON_9, 320, 210, 60, 60, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "message", ID_TEXT_0, 93, 39, 289, 29, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern int money;
extern int *random;
extern int mode;
char chMoneyRat[6];
char chTimeRat[6];
char chMessage[20];
bool startFlag;
bool button[9];
int countTimeRat;
int timeRat[2];
int chosen;
int point;

void countTime(WM_MESSAGE * pMsg)
{
	WM_HWIN hItem;
	timeRat[0]++;
	if (timeRat[0]>59)
	{
		timeRat[1]++;
		timeRat[0] = 0;
	}
	sprintf(chTimeRat, "%d:%d", timeRat[1], timeRat[0]);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
  EDIT_SetText(hItem, chTimeRat);
}

void ratUpDown(WM_MESSAGE * pMsg)
{
	WM_HWIN hItem;
	if (button[chosen])
	{
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1 + chosen);
	BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
	button[chosen] = false;
	}
	srand(*random);
	chosen = rand()%9;
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1 + chosen);
	BUTTON_SetBitmapEx(hItem, 0, &bmrat_up, 0 ,0);
	button[chosen] = true;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	case WM_TIMER: // 0.5ms
			if(startFlag && timeRat[1] != 1)
			{
				countTimeRat++;
				if(countTimeRat>=10)
				{
					countTimeRat = 0;
					countTime(pMsg);
				}
				if(countTimeRat == 7)
					ratUpDown(pMsg);
			}
			if (timeRat[1] == 1 && startFlag)
			{
				mode = 20;
				startFlag = false;
				money += (point);
				sprintf(chMessage, "Point: %d, you get $: %d", point, point);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				TEXT_SetText(hItem, chMessage);
				
				sprintf(chMoneyRat, "$: %d", money);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
				EDIT_SetText(hItem, chMoneyRat);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
				EDIT_SetText(hItem, "OVER");
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
				BUTTON_SetText(hItem, "OVER");
			}				
			WM_RestartTimer(pMsg->Data.v, 100);
		break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "0:0");
    EDIT_SetFont(hItem, GUI_FONT_20_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Money'
    //
		sprintf(chMoneyRat, "$: %d", money);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetFont(hItem, GUI_FONT_20_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		EDIT_SetText(hItem, chMoneyRat);
    //
    // Initialization of 'start_but'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Start");
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'but_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'message'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Point: 0");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'but_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    //
    // Initialization of 'but_9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetText(hItem, "");
		BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
    // USER START (Optionally insert additional code for further widget initialization)
		startFlag = false;
		timeRat[1] = timeRat[0] = 0;
		chosen = 0;
		point = 0;
		int index1;
		for (index1 = 0; index1 < 9; index1++)
			button[index1] = false;
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Money'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'start_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				startFlag = true;
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
				BUTTON_SetText(hItem, "Playing!");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'but_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[0] == true)
				{
					point++;
					button[0] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'but_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[1] == true)
					{
						point++;
						button[1] = false;
						sprintf(chMessage, "Point: %d", point);
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
						TEXT_SetText(hItem, chMessage);
						hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
						BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'but_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[2] == true)
				{
					point++;
					button[2] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'but_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[3] == true)
				{
					point++;
					button[3] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'but_5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[4] == true)
				{
					point++;
					button[4] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'but_6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[5] == true)
				{
					point++;
					button[5] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'but_7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[6] == true)
				{
					point++;
					button[6] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'but_8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[7] == true)
				{
					point++;
					button[7] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'but_9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (button[8] == true)
				{
					point++;
					button[8] = false;
					sprintf(chMessage, "Point: %d", point);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
					TEXT_SetText(hItem, chMessage);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
					BUTTON_SetBitmapEx(hItem, 0, &bmrat_down, 0 ,0);
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Creategame_rat
*/
WM_HWIN Creategame_rat(void);
WM_HWIN Creategame_rat(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin), 0, 100, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
